// src/errors/codes.ts

/**
 * Enum for error codes to ensure consistency across the library
 */
export enum ErrorCode {
  GENERIC = 'CAPTIONEER_ERROR',
  TOO_MANY_REQUESTS = 'CAPTIONEER_TOO_MANY_REQUESTS',
  VIDEO_UNAVAILABLE = 'CAPTIONEER_VIDEO_UNAVAILABLE',
  CAPTIONS_DISABLED = 'CAPTIONEER_CAPTIONS_DISABLED',
  CAPTIONS_NOT_AVAILABLE = 'CAPTIONEER_CAPTIONS_NOT_AVAILABLE',
  LANGUAGE_NOT_AVAILABLE = 'CAPTIONEER_LANGUAGE_NOT_AVAILABLE',
  INVALID_VIDEO_ID = 'CAPTIONEER_INVALID_VIDEO_ID',
  NETWORK_ERROR = 'CAPTIONEER_NETWORK_ERROR',
  PARSE_ERROR = 'CAPTIONEER_PARSE_ERROR',
}
